#!/usr/bin/env bash
# Bash script to configure Nginx for redirection

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@JanekateFitness permanent;' /etc/ngninx/sites-available/default
service nginx restart
