#!/usr/bin/env bash

# Install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Ensure that HAProxy can be managed via an init script

# Update and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Clear existing configuration
sudo truncate -s 0 /etc/haproxy/haproxy.cfg

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # SSL configurations
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend ngayep-frontend
    bind *:80
    mode http
    default_backend ngayep-backend

backend ngayep-backend
    balance roundrobin
    server 522732-web-01 52.91.122.106:80 check
    server 522732-web-02 54.209.142.112:80 check
EOF

# Enable HAProxy to be managed by an init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy service
sudo service haproxy restart

# Set the hostnames for the servers
sudo hostnamectl set-hostname 522732-web-01
echo "52.91.122.106 522732-web-01" | sudo tee -a /etc/hosts > /dev/null

sudo hostnamectl set-hostname 522732-web-02
echo "54.209.142.112 522732-web-02" | sudo tee -a /etc/hosts > /dev/null
