#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend myapp
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 522732-web-01 52.91.122.106:80 check
    server 522732-web-02 54.209.142.112:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
