#!/usr/bin/env bash
#script to tell a story with elements from file
passwd_file="/etc/passwd"

# Read the /etc/passwd file line by line using a while loop
while IFS=: read -r username _ uid gid info home shell; do
    # Print the required information
    echo "the user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $_, more info about the user here: $info"
echo
done < "$passwd_file"
