#!/usr/bin/env bash
#script that displays the content of the current  directory ina list format
files=$(ls)
for file in $files;do
	#use cut and sed to modify the file name
	modified_name=$(echo "$file" | cut -d '-' -f 2- | sed 's/^[[:space:]]*//')
echo "$modified_name"
done
