#!/usr/bin/env bash
#a script that gives info about the school file
file="school"
if [ ! -e "$file" ]; then
       echo "school file does not exist"
else
	echo "school file exists"
	if [ ! -s "$file" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$file" ]; then
			echo "school is a regular file"
	fi
fi	  
